name: project_19022022
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # global variables
  flutter_dotenv: ^5.0.2
  # network
  http: ^0.13.4
  # local storage
  shared_preferences: ^2.0.13
  # model template
  json_annotation: ^4.5.0
  # social login
  sign_in_with_apple: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#42a5f5"
  image: assets/images/ic_logo.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
  android12: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - .env.development
    - .env.production
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf

# CMD
# Splash generate: flutter pub run flutter_native_splash:create
# Model generate: flutter pub run build_runner build